########################## Docker compose to create a wordpress container. Uncomment the ports scope to publish
#### It needs a bridged network called a created network called wordpressnet with subnet 192.168.10.0/24
#### Change the IP if needed
#### Also, update the environment variables, and storage volume
version: '2'
services:
  wordpress:
    container_name: ahmedwordpress
    image: wordpress
    restart: always
    #ports:
    #- 8080:80
    networks:
            default:
                    ipv4_address: 192.168.10.10
    environment:
      WORDPRESS_DB_HOST: 172.17.0.1
      WORDPRESS_DB_USER: ahmedadmin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: ahmedwordpress
    volumes:
      - ahmedwordpress:/var/www/html/wp-content
volumes:
  ahmedwordpress:
networks:
        default:
                external:
                        name: wordpressnet
